import { PadGrid } from "./types";

export const initial2x2: PadGrid = [
  {
    id: "pad-0-0",
    label: "Kick",
    soundUrl: "kick.wav",
    color: "red",
    key: "r",
  },
  {
    id: "pad-0-1",
    label: "Snare",
    soundUrl: "snare.wav",
    color: "blue",
    key: "t",
  },
  {
    id: "pad-1-0",
    label: "HiHat",
    soundUrl: "hihat.wav",
    color: "green",
    key: "f",
  },
  {
    id: "pad-1-1",
    label: "Clap",
    soundUrl: "clap.wav",
    color: "yellow",
    key: "g",
  },
];

export const initial3x3: PadGrid = [
  {
    id: "pad-0-0",
    label: "Kick",
    soundUrl: "/sounds/kick.wav",
    color: "red",
    key: "R",
  },
  {
    id: "pad-0-1",
    label: "Snare",
    soundUrl: "/sounds/snare.wav",
    color: "blue",
    key: "T",
  },
  {
    id: "pad-0-2",
    label: "HiHat",
    soundUrl: "/sounds/hihat.wav",
    color: "green",
    key: "Y",
  },
  {
    id: "pad-1-0",
    label: "Clap",
    soundUrl: "/sounds/clap.wav",
    color: "yellow",
    key: "F",
  },
  {
    id: "pad-1-1",
    label: "Crash",
    soundUrl: "/sounds/crash.wav",
    color: "purple",
    key: "G",
  },
  {
    id: "pad-1-2",
    label: "Open Hat",
    soundUrl: "/sounds/openhat.wav",
    color: "orange",
    key: "H",
  },
  {
    id: "pad-2-0",
    label: "Perc 1",
    soundUrl: "/sounds/perc1.wav",
    color: "pink",
    key: "V",
  },
  {
    id: "pad-2-1",
    label: "Perc 2",
    soundUrl: "/sounds/perc2.wav",
    color: "cyan",
    key: "B",
  },
  {
    id: "pad-2-2",
    label: "Bass",
    soundUrl: "/sounds/bass.wav",
    color: "indigo",
    key: "N",
  },
];

export const initial4x4: PadGrid = [
  {
    id: "pad-0-0",
    label: "Kick",
    soundUrl: "/sounds/kick.wav",
    color: "red",
    key: "4",
  },
  {
    id: "pad-0-1",
    label: "Snare",
    soundUrl: "/sounds/snare.wav",
    color: "blue",
    key: "5",
  },
  {
    id: "pad-0-2",
    label: "HiHat",
    soundUrl: "/sounds/hihat.wav",
    color: "green",
    key: "6",
  },
  {
    id: "pad-0-3",
    label: "Clap",
    soundUrl: "/sounds/clap.wav",
    color: "yellow",
    key: "7",
  },
  {
    id: "pad-1-0",
    label: "Crash",
    soundUrl: "/sounds/crash.wav",
    color: "purple",
    key: "R",
  },
  {
    id: "pad-1-1",
    label: "Open Hat",
    soundUrl: "/sounds/openhat.wav",
    color: "orange",
    key: "T",
  },
  {
    id: "pad-1-2",
    label: "Perc 1",
    soundUrl: "/sounds/perc1.wav",
    color: "pink",
    key: "Y",
  },
  {
    id: "pad-1-3",
    label: "Perc 2",
    soundUrl: "/sounds/perc2.wav",
    color: "cyan",
    key: "U",
  },
  {
    id: "pad-2-0",
    label: "Bass",
    soundUrl: "/sounds/bass.wav",
    color: "indigo",
    key: "F",
  },
  {
    id: "pad-2-1",
    label: "Lead",
    soundUrl: "/sounds/lead.wav",
    color: "teal",
    key: "G",
  },
  {
    id: "pad-2-2",
    label: "Pad",
    soundUrl: "/sounds/pad.wav",
    color: "lime",
    key: "H",
  },
  {
    id: "pad-2-3",
    label: "FX",
    soundUrl: "/sounds/fx.wav",
    color: "amber",
    key: "J",
  },
  {
    id: "pad-3-0",
    label: "Vocal 1",
    soundUrl: "/sounds/vocal1.wav",
    color: "rose",
    key: "V",
  },
  {
    id: "pad-3-1",
    label: "Vocal 2",
    soundUrl: "/sounds/vocal2.wav",
    color: "violet",
    key: "B",
  },
  {
    id: "pad-3-2",
    label: "Synth 1",
    soundUrl: "/sounds/synth1.wav",
    color: "emerald",
    key: "N",
  },
  {
    id: "pad-3-3",
    label: "Synth 2",
    soundUrl: "/sounds/synth2.wav",
    color: "sky",
    key: "M",
  },
];

export const presetsBySize = {
  2: initial2x2,
  3: initial3x3,
  4: initial4x4,
} as const;
